services:
  postgres:
    image: postgres:17-alpine
    restart: unless-stopped
    ports:
      - "6666:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: waku
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
