import type { TemplateDocument } from "@/components/template-editor/types";

export type SeedTemplate = {
  id: string;
  name: string;
  description: string;
  tags: readonly string[];
  document: TemplateDocument;
};

const blogPostDoc: TemplateDocument = {
  artboard: { width: 1200, height: 630, background: "#0f172a" },
  nodes: [
    {
      id: "n1",
      name: "Title",
      type: "text",
      x: 80,
      y: 220,
      width: 1040,
      height: 160,
      rotation: 0,
      opacity: 1,
      visible: true,
      locked: false,
      text: { $param: "title", default: "Your blog post title" },
      fontSize: 84,
      fontWeight: 700,
      italic: false,
      color: "#ffffff",
      align: "left",
      fontFamily: "Inter",
      letterSpacing: -2,
      lineHeight: 1.05,
    },
    {
      id: "n2",
      name: "Author",
      type: "text",
      x: 80,
      y: 460,
      width: 1040,
      height: 40,
      rotation: 0,
      opacity: 1,
      visible: true,
      locked: false,
      text: { $param: "author", default: "by @you" },
      fontSize: 28,
      fontWeight: 500,
      italic: false,
      color: "#94a3b8",
      align: "left",
      fontFamily: "Inter",
      letterSpacing: 0,
      lineHeight: 1.2,
    },
  ],
  paramsSchema: {
    title: { kind: "string", default: "Your blog post title", maxLen: 120 },
    author: { kind: "string", default: "by @you", maxLen: 60 },
  },
};

const productLaunchDoc: TemplateDocument = {
  artboard: { width: 1200, height: 630, background: "#7c5cff" },
  nodes: [
    {
      id: "r1",
      name: "Card",
      type: "rectangle",
      x: 80,
      y: 80,
      width: 1040,
      height: 470,
      rotation: 0,
      opacity: 1,
      visible: true,
      locked: false,
      fill: "#ffffff",
      stroke: "#000000",
      strokeWidth: 0,
      cornerRadius: 32,
    },
    {
      id: "t1",
      name: "Eyebrow",
      type: "text",
      x: 130,
      y: 130,
      width: 940,
      height: 36,
      rotation: 0,
      opacity: 1,
      visible: true,
      locked: false,
      text: { $param: "eyebrow", default: "NOW LAUNCHING" },
      fontSize: 22,
      fontWeight: 600,
      italic: false,
      color: "#7c5cff",
      align: "left",
      fontFamily: "Inter",
      letterSpacing: 4,
      lineHeight: 1.2,
    },
    {
      id: "t2",
      name: "Title",
      type: "text",
      x: 130,
      y: 200,
      width: 940,
      height: 200,
      rotation: 0,
      opacity: 1,
      visible: true,
      locked: false,
      text: { $param: "title", default: "Ship faster" },
      fontSize: 120,
      fontWeight: 800,
      italic: false,
      color: "#0f172a",
      align: "left",
      fontFamily: "Inter",
      letterSpacing: -4,
      lineHeight: 1,
    },
    {
      id: "t3",
      name: "Tagline",
      type: "text",
      x: 130,
      y: 430,
      width: 940,
      height: 60,
      rotation: 0,
      opacity: 1,
      visible: true,
      locked: false,
      text: {
        $param: "tagline",
        default: "Your tagline goes here. Make it count.",
      },
      fontSize: 28,
      fontWeight: 400,
      italic: false,
      color: "#475569",
      align: "left",
      fontFamily: "Inter",
      letterSpacing: 0,
      lineHeight: 1.3,
    },
  ],
  paramsSchema: {
    eyebrow: { kind: "string", default: "NOW LAUNCHING", maxLen: 32 },
    title: { kind: "string", default: "Ship faster", maxLen: 40 },
    tagline: {
      kind: "string",
      default: "Your tagline goes here. Make it count.",
      maxLen: 120,
    },
  },
};

const quoteCardDoc: TemplateDocument = {
  artboard: { width: 1200, height: 630, background: "#fef3c7" },
  nodes: [
    {
      id: "q1",
      name: "Quote",
      type: "text",
      x: 100,
      y: 160,
      width: 1000,
      height: 280,
      rotation: 0,
      opacity: 1,
      visible: true,
      locked: false,
      text: {
        $param: "quote",
        default: "“The best way to predict the future is to invent it.”",
      },
      fontSize: 64,
      fontWeight: 600,
      italic: true,
      color: "#1e293b",
      align: "center",
      fontFamily: "Inter",
      letterSpacing: -1,
      lineHeight: 1.15,
    },
    {
      id: "q2",
      name: "Attribution",
      type: "text",
      x: 100,
      y: 480,
      width: 1000,
      height: 40,
      rotation: 0,
      opacity: 1,
      visible: true,
      locked: false,
      text: { $param: "author", default: "— Alan Kay" },
      fontSize: 28,
      fontWeight: 500,
      italic: false,
      color: "#78716c",
      align: "center",
      fontFamily: "Inter",
      letterSpacing: 0,
      lineHeight: 1.2,
    },
  ],
  paramsSchema: {
    quote: {
      kind: "string",
      default: "“The best way to predict the future is to invent it.”",
      maxLen: 200,
    },
    author: { kind: "string", default: "— Alan Kay", maxLen: 60 },
  },
};

const minimalLogoDoc: TemplateDocument = {
  artboard: { width: 1200, height: 630, background: "#ffffff" },
  nodes: [
    {
      id: "c1",
      name: "Accent",
      type: "ellipse",
      x: 540,
      y: 180,
      width: 120,
      height: 120,
      rotation: 0,
      opacity: 1,
      visible: true,
      locked: false,
      fill: "#7c5cff",
      stroke: "#000000",
      strokeWidth: 0,
    },
    {
      id: "h1",
      name: "Headline",
      type: "text",
      x: 80,
      y: 330,
      width: 1040,
      height: 100,
      rotation: 0,
      opacity: 1,
      visible: true,
      locked: false,
      text: { $param: "headline", default: "Less is more." },
      fontSize: 72,
      fontWeight: 700,
      italic: false,
      color: "#0f172a",
      align: "center",
      fontFamily: "Inter",
      letterSpacing: -2,
      lineHeight: 1.1,
    },
    {
      id: "h2",
      name: "Sub",
      type: "text",
      x: 80,
      y: 450,
      width: 1040,
      height: 40,
      rotation: 0,
      opacity: 1,
      visible: true,
      locked: false,
      text: { $param: "sub", default: "A minimal opener." },
      fontSize: 24,
      fontWeight: 400,
      italic: false,
      color: "#64748b",
      align: "center",
      fontFamily: "Inter",
      letterSpacing: 1,
      lineHeight: 1.2,
    },
  ],
  paramsSchema: {
    headline: { kind: "string", default: "Less is more.", maxLen: 60 },
    sub: { kind: "string", default: "A minimal opener.", maxLen: 80 },
  },
};

export const SEED_TEMPLATES: readonly SeedTemplate[] = [
  {
    id: "blog-post",
    name: "Blog post",
    description: "Bold title on dark — perfect for article shares.",
    tags: ["dark", "editorial", "blog"],
    document: blogPostDoc,
  },
  {
    id: "product-launch",
    name: "Product launch",
    description: "Card on color with eyebrow, headline, and tagline.",
    tags: ["launch", "marketing", "vivid"],
    document: productLaunchDoc,
  },
  {
    id: "quote-card",
    name: "Quote card",
    description: "Centered serif-feel quote with attribution.",
    tags: ["quote", "warm", "centered"],
    document: quoteCardDoc,
  },
  {
    id: "minimal-opener",
    name: "Minimal opener",
    description: "Single accent dot, big headline, soft subline.",
    tags: ["minimal", "light", "clean"],
    document: minimalLogoDoc,
  },
];
