import type { TemplateDocument } from "@/components/template-editor/types";
import { flatPaint } from "@/components/template-editor/types";

export type SeedTemplate = {
  id: string;
  name: string;
  description: string;
  tags: readonly string[];
  document: TemplateDocument;
};

const blogPostDoc: TemplateDocument = {
  artboard: { width: 1200, height: 630, background: flatPaint("#0f172a") },
  nodes: [
    {
      id: "n1",
      name: "Title",
      type: "text",
      x: 80,
      y: 220,
      width: 1040,
      height: 160,
      rotation: 0,
      opacity: 1,
      visible: true,
      locked: false,
      text: { $param: "title", default: "Your blog post title" },
      fontSize: 84,
      fontWeight: 700,
      italic: false,
      color: flatPaint("#ffffff"),
      align: "left",
      fontFamily: "Inter",
      letterSpacing: -2,
      lineHeight: 1.05,
    },
    {
      id: "n2",
      name: "Author",
      type: "text",
      x: 80,
      y: 460,
      width: 1040,
      height: 40,
      rotation: 0,
      opacity: 1,
      visible: true,
      locked: false,
      text: { $param: "author", default: "by @you" },
      fontSize: 28,
      fontWeight: 500,
      italic: false,
      color: flatPaint("#94a3b8"),
      align: "left",
      fontFamily: "Inter",
      letterSpacing: 0,
      lineHeight: 1.2,
    },
  ],
  paramsSchema: {
    title: { kind: "string", default: "Your blog post title", maxLen: 120 },
    author: { kind: "string", default: "by @you", maxLen: 60 },
  },
};

const productLaunchDoc: TemplateDocument = {
  artboard: { width: 1200, height: 630, background: flatPaint("#7c5cff") },
  nodes: [
    {
      id: "r1",
      name: "Card",
      type: "rectangle",
      x: 80,
      y: 80,
      width: 1040,
      height: 470,
      rotation: 0,
      opacity: 1,
      visible: true,
      locked: false,
      fill: flatPaint("#ffffff"),
      stroke: flatPaint("#000000"),
      strokeWidth: 0,
      cornerRadius: 32,
    },
    {
      id: "t1",
      name: "Eyebrow",
      type: "text",
      x: 130,
      y: 130,
      width: 940,
      height: 36,
      rotation: 0,
      opacity: 1,
      visible: true,
      locked: false,
      text: { $param: "eyebrow", default: "NOW LAUNCHING" },
      fontSize: 22,
      fontWeight: 600,
      italic: false,
      color: flatPaint("#7c5cff"),
      align: "left",
      fontFamily: "Inter",
      letterSpacing: 4,
      lineHeight: 1.2,
    },
    {
      id: "t2",
      name: "Title",
      type: "text",
      x: 130,
      y: 200,
      width: 940,
      height: 200,
      rotation: 0,
      opacity: 1,
      visible: true,
      locked: false,
      text: { $param: "title", default: "Ship faster" },
      fontSize: 120,
      fontWeight: 800,
      italic: false,
      color: flatPaint("#0f172a"),
      align: "left",
      fontFamily: "Inter",
      letterSpacing: -4,
      lineHeight: 1,
    },
    {
      id: "t3",
      name: "Tagline",
      type: "text",
      x: 130,
      y: 430,
      width: 940,
      height: 60,
      rotation: 0,
      opacity: 1,
      visible: true,
      locked: false,
      text: {
        $param: "tagline",
        default: "Your tagline goes here. Make it count.",
      },
      fontSize: 28,
      fontWeight: 400,
      italic: false,
      color: flatPaint("#475569"),
      align: "left",
      fontFamily: "Inter",
      letterSpacing: 0,
      lineHeight: 1.3,
    },
  ],
  paramsSchema: {
    eyebrow: { kind: "string", default: "NOW LAUNCHING", maxLen: 32 },
    title: { kind: "string", default: "Ship faster", maxLen: 40 },
    tagline: {
      kind: "string",
      default: "Your tagline goes here. Make it count.",
      maxLen: 120,
    },
  },
};

const quoteCardDoc: TemplateDocument = {
  artboard: { width: 1200, height: 630, background: flatPaint("#fef3c7") },
  nodes: [
    {
      id: "q1",
      name: "Quote",
      type: "text",
      x: 100,
      y: 160,
      width: 1000,
      height: 280,
      rotation: 0,
      opacity: 1,
      visible: true,
      locked: false,
      text: {
        $param: "quote",
        default: "“The best way to predict the future is to invent it.”",
      },
      fontSize: 64,
      fontWeight: 600,
      italic: true,
      color: flatPaint("#1e293b"),
      align: "center",
      fontFamily: "Inter",
      letterSpacing: -1,
      lineHeight: 1.15,
    },
    {
      id: "q2",
      name: "Attribution",
      type: "text",
      x: 100,
      y: 480,
      width: 1000,
      height: 40,
      rotation: 0,
      opacity: 1,
      visible: true,
      locked: false,
      text: { $param: "author", default: "— Alan Kay" },
      fontSize: 28,
      fontWeight: 500,
      italic: false,
      color: flatPaint("#78716c"),
      align: "center",
      fontFamily: "Inter",
      letterSpacing: 0,
      lineHeight: 1.2,
    },
  ],
  paramsSchema: {
    quote: {
      kind: "string",
      default: "“The best way to predict the future is to invent it.”",
      maxLen: 200,
    },
    author: { kind: "string", default: "— Alan Kay", maxLen: 60 },
  },
};

const minimalLogoDoc: TemplateDocument = {
  artboard: { width: 1200, height: 630, background: flatPaint("#ffffff") },
  nodes: [
    {
      id: "c1",
      name: "Accent",
      type: "ellipse",
      x: 540,
      y: 180,
      width: 120,
      height: 120,
      rotation: 0,
      opacity: 1,
      visible: true,
      locked: false,
      fill: flatPaint("#7c5cff"),
      stroke: flatPaint("#000000"),
      strokeWidth: 0,
    },
    {
      id: "h1",
      name: "Headline",
      type: "text",
      x: 80,
      y: 330,
      width: 1040,
      height: 100,
      rotation: 0,
      opacity: 1,
      visible: true,
      locked: false,
      text: { $param: "headline", default: "Less is more." },
      fontSize: 72,
      fontWeight: 700,
      italic: false,
      color: flatPaint("#0f172a"),
      align: "center",
      fontFamily: "Inter",
      letterSpacing: -2,
      lineHeight: 1.1,
    },
    {
      id: "h2",
      name: "Sub",
      type: "text",
      x: 80,
      y: 450,
      width: 1040,
      height: 40,
      rotation: 0,
      opacity: 1,
      visible: true,
      locked: false,
      text: { $param: "sub", default: "A minimal opener." },
      fontSize: 24,
      fontWeight: 400,
      italic: false,
      color: flatPaint("#64748b"),
      align: "center",
      fontFamily: "Inter",
      letterSpacing: 1,
      lineHeight: 1.2,
    },
  ],
  paramsSchema: {
    headline: { kind: "string", default: "Less is more.", maxLen: 60 },
    sub: { kind: "string", default: "A minimal opener.", maxLen: 80 },
  },
};

const techArtistDoc: TemplateDocument = {
  artboard: { width: 1200, height: 630, background: flatPaint("#ffffff") },
  nodes: [
    {
      id: "photo",
      name: "Portrait",
      type: "image",
      x: 0,
      y: 0,
      width: 470,
      height: 630,
      rotation: 0,
      opacity: 1,
      visible: true,
      locked: false,
      src: {
        $param: "photo",
        default:
          "https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=900&q=80",
      },
      fit: "cover",
      cornerRadius: 0,
      stroke: flatPaint("#000000"),
      strokeWidth: 0,
      shadow: null,
    },
    {
      id: "panel",
      name: "Panel",
      type: "rectangle",
      x: 470,
      y: 0,
      width: 730,
      height: 630,
      rotation: 0,
      opacity: 1,
      visible: true,
      locked: false,
      fill: flatPaint("#f4f4f3"),
      stroke: flatPaint("#000000"),
      strokeWidth: 0,
      cornerRadius: 0,
    },
    {
      id: "headline",
      name: "Headline",
      type: "text",
      x: 540,
      y: 175,
      width: 580,
      height: 170,
      rotation: 0,
      opacity: 1,
      visible: true,
      locked: false,
      text: { $param: "headline", default: "TECH ARTIST & 3D WEB DEV" },
      fontSize: 56,
      fontWeight: 600,
      italic: false,
      color: flatPaint("#18181b"),
      align: "left",
      fontFamily: "Inter",
      letterSpacing: -1,
      lineHeight: 1.12,
    },
    {
      id: "bio",
      name: "Bio",
      type: "text",
      x: 540,
      y: 380,
      width: 540,
      height: 170,
      rotation: 0,
      opacity: 1,
      visible: true,
      locked: false,
      text: {
        $param: "bio",
        default:
          "INDEPENDENT CRAFTER, PERFECT FOR COMPANIES LOOKING TO CATALYZE SOME MAGIC. IF YOUR VISION INVOLVES 3D — I CAN HELP YOU BRING IT TO LIFE, USUALLY FROM SCRATCH.",
      },
      fontSize: 15,
      fontWeight: 400,
      italic: false,
      color: flatPaint("#8a8a8a"),
      align: "left",
      fontFamily: "JetBrains Mono",
      letterSpacing: 1,
      lineHeight: 1.7,
    },
  ],
  paramsSchema: {
    photo: {
      kind: "string",
      default:
        "https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=900&q=80",
    },
    headline: {
      kind: "string",
      default: "TECH ARTIST & 3D WEB DEV",
      maxLen: 60,
    },
    bio: {
      kind: "string",
      default:
        "INDEPENDENT CRAFTER, PERFECT FOR COMPANIES LOOKING TO CATALYZE SOME MAGIC. IF YOUR VISION INVOLVES 3D — I CAN HELP YOU BRING IT TO LIFE, USUALLY FROM SCRATCH.",
      maxLen: 240,
    },
  },
};

const feelsCoverDoc: TemplateDocument = {
  artboard: { width: 1200, height: 630, background: flatPaint("#111111") },
  nodes: [
    {
      id: "photo",
      name: "Cover photo",
      type: "image",
      x: 0,
      y: 0,
      width: 1200,
      height: 630,
      rotation: 0,
      opacity: 1,
      visible: true,
      locked: false,
      src: {
        $param: "photo",
        default:
          "https://images.unsplash.com/photo-1492684223066-81342ee5ff30?w=1400&q=80",
      },
      fit: "cover",
      cornerRadius: 0,
      stroke: flatPaint("#000000"),
      strokeWidth: 0,
      shadow: null,
    },
    {
      id: "scrim",
      name: "Scrim",
      type: "rectangle",
      x: 0,
      y: 0,
      width: 1200,
      height: 630,
      rotation: 0,
      opacity: 0.18,
      visible: true,
      locked: false,
      fill: flatPaint("#000000"),
      stroke: flatPaint("#000000"),
      strokeWidth: 0,
      cornerRadius: 0,
    },
    {
      id: "mark",
      name: "Leaf mark",
      type: "path",
      x: 455,
      y: 255,
      width: 96,
      height: 96,
      rotation: 0,
      opacity: 1,
      visible: true,
      locked: false,
      fill: flatPaint("#ffffff"),
      stroke: flatPaint("#000000"),
      strokeWidth: 0,
      d: "M50 4 C 80 28 80 72 50 96 C 20 72 20 28 50 4 Z",
      viewBox: [100, 100],
    },
    {
      id: "brand",
      name: "Wordmark",
      type: "text",
      x: 560,
      y: 248,
      width: 420,
      height: 120,
      rotation: 0,
      opacity: 1,
      visible: true,
      locked: false,
      text: { $param: "brand", default: "Feels" },
      fontSize: 104,
      fontWeight: 700,
      italic: false,
      color: flatPaint("#ffffff"),
      align: "left",
      fontFamily: "Inter",
      letterSpacing: -4,
      lineHeight: 1,
    },
  ],
  paramsSchema: {
    photo: {
      kind: "string",
      default:
        "https://images.unsplash.com/photo-1492684223066-81342ee5ff30?w=1400&q=80",
    },
    brand: { kind: "string", default: "Feels", maxLen: 24 },
  },
};

const pebloShowcaseDoc: TemplateDocument = {
  artboard: { width: 1200, height: 630, background: flatPaint("#d7f23a") },
  nodes: [
    {
      id: "mark",
      name: "Logo mark",
      type: "path",
      x: 438,
      y: 64,
      width: 56,
      height: 56,
      rotation: 0,
      opacity: 1,
      visible: true,
      locked: false,
      fill: flatPaint("#111111"),
      stroke: flatPaint("#000000"),
      strokeWidth: 0,
      d: "M30 10 H60 C82 10 82 54 60 54 H46 V92 H30 Z",
      viewBox: [100, 100],
    },
    {
      id: "brand",
      name: "Brand",
      type: "text",
      x: 506,
      y: 60,
      width: 280,
      height: 70,
      rotation: 0,
      opacity: 1,
      visible: true,
      locked: false,
      text: { $param: "brand", default: "Peblo" },
      fontSize: 56,
      fontWeight: 700,
      italic: false,
      color: flatPaint("#111111"),
      align: "left",
      fontFamily: "Inter",
      letterSpacing: -2,
      lineHeight: 1,
    },
    {
      id: "card",
      name: "Dashboard card",
      type: "rectangle",
      x: 150,
      y: 200,
      width: 740,
      height: 390,
      rotation: 0,
      opacity: 1,
      visible: true,
      locked: false,
      fill: flatPaint("#ffffff"),
      stroke: flatPaint("#000000"),
      strokeWidth: 0,
      cornerRadius: 18,
      shadow: { offsetX: 0, offsetY: 24, blur: 48, color: "rgba(0,0,0,0.18)" },
    },
    {
      id: "card-title",
      name: "Card title",
      type: "text",
      x: 190,
      y: 238,
      width: 400,
      height: 36,
      rotation: 0,
      opacity: 1,
      visible: true,
      locked: false,
      text: { $param: "heading", default: "Brand deals" },
      fontSize: 24,
      fontWeight: 700,
      italic: false,
      color: flatPaint("#0f172a"),
      align: "left",
      fontFamily: "Inter",
      letterSpacing: -0.5,
      lineHeight: 1.2,
    },
    {
      id: "stat1",
      name: "Stat 1",
      type: "rectangle",
      x: 190,
      y: 292,
      width: 200,
      height: 80,
      rotation: 0,
      opacity: 1,
      visible: true,
      locked: false,
      fill: flatPaint("#f4f4f5"),
      stroke: flatPaint("#000000"),
      strokeWidth: 0,
      cornerRadius: 12,
    },
    {
      id: "stat1-v",
      name: "Stat 1 value",
      type: "text",
      x: 190,
      y: 320,
      width: 200,
      height: 30,
      rotation: 0,
      opacity: 1,
      visible: true,
      locked: false,
      text: "$8.31m",
      fontSize: 24,
      fontWeight: 700,
      italic: false,
      color: flatPaint("#111111"),
      align: "center",
      fontFamily: "Inter",
      letterSpacing: -0.5,
      lineHeight: 1.2,
    },
    {
      id: "stat2",
      name: "Stat 2",
      type: "rectangle",
      x: 410,
      y: 292,
      width: 200,
      height: 80,
      rotation: 0,
      opacity: 1,
      visible: true,
      locked: false,
      fill: flatPaint("#f4f4f5"),
      stroke: flatPaint("#000000"),
      strokeWidth: 0,
      cornerRadius: 12,
    },
    {
      id: "stat2-v",
      name: "Stat 2 value",
      type: "text",
      x: 410,
      y: 320,
      width: 200,
      height: 30,
      rotation: 0,
      opacity: 1,
      visible: true,
      locked: false,
      text: "$412,130",
      fontSize: 24,
      fontWeight: 700,
      italic: false,
      color: flatPaint("#111111"),
      align: "center",
      fontFamily: "Inter",
      letterSpacing: -0.5,
      lineHeight: 1.2,
    },
    {
      id: "stat3",
      name: "Stat 3",
      type: "rectangle",
      x: 630,
      y: 292,
      width: 200,
      height: 80,
      rotation: 0,
      opacity: 1,
      visible: true,
      locked: false,
      fill: flatPaint("#f4f4f5"),
      stroke: flatPaint("#000000"),
      strokeWidth: 0,
      cornerRadius: 12,
    },
    {
      id: "stat3-v",
      name: "Stat 3 value",
      type: "text",
      x: 630,
      y: 320,
      width: 200,
      height: 30,
      rotation: 0,
      opacity: 1,
      visible: true,
      locked: false,
      text: "$82.25m",
      fontSize: 24,
      fontWeight: 700,
      italic: false,
      color: flatPaint("#111111"),
      align: "center",
      fontFamily: "Inter",
      letterSpacing: -0.5,
      lineHeight: 1.2,
    },
    {
      id: "row1-bar",
      name: "Row 1 bar",
      type: "rectangle",
      x: 190,
      y: 432,
      width: 360,
      height: 10,
      rotation: 0,
      opacity: 1,
      visible: true,
      locked: false,
      fill: flatPaint("#e5e7eb"),
      stroke: flatPaint("#000000"),
      strokeWidth: 0,
      cornerRadius: 5,
    },
    {
      id: "row1-v",
      name: "Row 1 value",
      type: "text",
      x: 630,
      y: 422,
      width: 200,
      height: 30,
      rotation: 0,
      opacity: 1,
      visible: true,
      locked: false,
      text: "$12,000",
      fontSize: 20,
      fontWeight: 600,
      italic: false,
      color: flatPaint("#16a34a"),
      align: "right",
      fontFamily: "Inter",
      letterSpacing: 0,
      lineHeight: 1.2,
    },
    {
      id: "row2-bar",
      name: "Row 2 bar",
      type: "rectangle",
      x: 190,
      y: 492,
      width: 360,
      height: 10,
      rotation: 0,
      opacity: 1,
      visible: true,
      locked: false,
      fill: flatPaint("#e5e7eb"),
      stroke: flatPaint("#000000"),
      strokeWidth: 0,
      cornerRadius: 5,
    },
    {
      id: "row2-v",
      name: "Row 2 value",
      type: "text",
      x: 630,
      y: 482,
      width: 200,
      height: 30,
      rotation: 0,
      opacity: 1,
      visible: true,
      locked: false,
      text: "$22,000",
      fontSize: 20,
      fontWeight: 600,
      italic: false,
      color: flatPaint("#16a34a"),
      align: "right",
      fontFamily: "Inter",
      letterSpacing: 0,
      lineHeight: 1.2,
    },
    {
      id: "card2",
      name: "Mini card",
      type: "rectangle",
      x: 910,
      y: 260,
      width: 240,
      height: 300,
      rotation: 0,
      opacity: 1,
      visible: true,
      locked: false,
      fill: flatPaint("#ffffff"),
      stroke: flatPaint("#000000"),
      strokeWidth: 0,
      cornerRadius: 16,
      shadow: { offsetX: 0, offsetY: 20, blur: 40, color: "rgba(0,0,0,0.16)" },
    },
    {
      id: "card2-title",
      name: "Mini title",
      type: "text",
      x: 935,
      y: 292,
      width: 190,
      height: 24,
      rotation: 0,
      opacity: 1,
      visible: true,
      locked: false,
      text: "Brand deals",
      fontSize: 15,
      fontWeight: 700,
      italic: false,
      color: flatPaint("#0f172a"),
      align: "left",
      fontFamily: "Inter",
      letterSpacing: -0.3,
      lineHeight: 1.2,
    },
    {
      id: "card2-p1",
      name: "Mini stat 1",
      type: "rectangle",
      x: 935,
      y: 328,
      width: 92,
      height: 48,
      rotation: 0,
      opacity: 1,
      visible: true,
      locked: false,
      fill: flatPaint("#f4f4f5"),
      stroke: flatPaint("#000000"),
      strokeWidth: 0,
      cornerRadius: 8,
    },
    {
      id: "card2-p2",
      name: "Mini stat 2",
      type: "rectangle",
      x: 1037,
      y: 328,
      width: 92,
      height: 48,
      rotation: 0,
      opacity: 1,
      visible: true,
      locked: false,
      fill: flatPaint("#f4f4f5"),
      stroke: flatPaint("#000000"),
      strokeWidth: 0,
      cornerRadius: 8,
    },
    {
      id: "card2-b1",
      name: "Mini row 1",
      type: "rectangle",
      x: 935,
      y: 412,
      width: 150,
      height: 8,
      rotation: 0,
      opacity: 1,
      visible: true,
      locked: false,
      fill: flatPaint("#e5e7eb"),
      stroke: flatPaint("#000000"),
      strokeWidth: 0,
      cornerRadius: 4,
    },
    {
      id: "card2-b2",
      name: "Mini row 2",
      type: "rectangle",
      x: 935,
      y: 452,
      width: 150,
      height: 8,
      rotation: 0,
      opacity: 1,
      visible: true,
      locked: false,
      fill: flatPaint("#e5e7eb"),
      stroke: flatPaint("#000000"),
      strokeWidth: 0,
      cornerRadius: 4,
    },
  ],
  paramsSchema: {
    brand: { kind: "string", default: "Peblo", maxLen: 24 },
    heading: { kind: "string", default: "Brand deals", maxLen: 32 },
  },
};

export const SEED_TEMPLATES: readonly SeedTemplate[] = [
  {
    id: "blog-post",
    name: "Blog post",
    description: "Bold title on dark — perfect for article shares.",
    tags: ["dark", "editorial", "blog"],
    document: blogPostDoc,
  },
  {
    id: "product-launch",
    name: "Product launch",
    description: "Card on color with eyebrow, headline, and tagline.",
    tags: ["launch", "marketing", "vivid"],
    document: productLaunchDoc,
  },
  {
    id: "quote-card",
    name: "Quote card",
    description: "Centered serif-feel quote with attribution.",
    tags: ["quote", "warm", "centered"],
    document: quoteCardDoc,
  },
  {
    id: "minimal-opener",
    name: "Minimal opener",
    description: "Single accent dot, big headline, soft subline.",
    tags: ["minimal", "light", "clean"],
    document: minimalLogoDoc,
  },
  {
    id: "tech-artist",
    name: "Tech artist",
    description: "Split portrait + light panel with mono bio — portfolio card.",
    tags: ["portfolio", "split", "editorial"],
    document: techArtistDoc,
  },
  {
    id: "feels-cover",
    name: "Photo brand cover",
    description: "Full-bleed photo with centered logo mark and wordmark.",
    tags: ["brand", "photo", "bold"],
    document: feelsCoverDoc,
  },
  {
    id: "peblo-showcase",
    name: "SaaS showcase",
    description: "Lime brand header with a dashboard UI mockup.",
    tags: ["saas", "product", "vivid"],
    document: pebloShowcaseDoc,
  },
];
